# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20161201_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('P', 'In progress'), ('C', 'Completed')], max_length=1),
        ),
    ]
